[project]
name = "bostatest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "breno-fig", email = "brenoicarocf@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.52",
    "typing>=3.10.0.0",
    "validators>=0.35.0",
]

[tool.fastapi]
entrypoint = "src.main:app" #shows entrypoint


[tool.uv.workspace]
members = [
    "bostatest",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
